# Generated by Django 3.0.4 on 2020-03-18 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import studentportal.decorators
import studentportal.models
import studentportal.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('link', models.URLField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('category', models.ForeignKey(null=True, on_delete=models.SET(studentportal.models._get_other_category), related_name='NGOs', to='studentportal.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('credits', models.IntegerField(default=2, validators=[studentportal.validators.validate_credits])),
                ('NGO_name', models.CharField(max_length=1000)),
                ('NGO_details', models.CharField(max_length=1000)),
                ('NGO_super', models.CharField(max_length=1000)),
                ('NGO_super_contact', models.CharField(max_length=100)),
                ('goals', models.TextField()),
                ('schedule_text', models.TextField()),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('stage', models.IntegerField(default=1)),
                ('deleted', models.BooleanField(default=False)),
                ('NGO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='studentportal.NGO')),
                ('category', models.ForeignKey(on_delete=models.SET(studentportal.models._get_other_category), related_name='projects', to='studentportal.Category')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('all_projects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='feedback', serialize=False, to='studentportal.Project')),
                ('hours', models.IntegerField(validators=[studentportal.validators.validate_feedback_hours])),
                ('achievements', models.TextField(max_length=2000)),
                ('experience', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_text', models.TextField(blank=True, max_length=2000)),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='studentportal.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=studentportal.decorators._PathAndRename('uploads/%Y/'))),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='studentportal.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestions', models.TextField(blank=True, max_length=2000)),
                ('rating', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
